name: resident_live
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

scripts: 
  gen: dart run build_runner watch
  run: flutter run -t lib/app/main.dart --dart-define-from-file=.env
  run-release: flutter run -t lib/app/main.dart --release
  deploy: cd ios && fastlane beta
  clean: |
    flutter clean 
    flutter pub get

dependencies:
  domain:
    path: ../domain

  data: 
    path: ../data
    
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  bloc: ^8.1.4
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  apple_maps_flutter: ^1.2.0
 
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  sentry_flutter: ^8.14.2


  
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.2.8

  modal_bottom_sheet: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.69.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  app_settings: ^5.1.1
  soft_edge_blur: ^0.1.3
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  provider: ^6.1.5
  get_it: ^7.7.0
  injectable: ^2.5.0
  country_code_picker: ^3.3.0
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  skeletonizer: ^2.0.1
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  gaimon: ^1.4.1
  cached_network_image: ^3.4.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  chopper_generator: ^7.0.4

  dependency_validator: any
  injectable_generator: ^2.6.2
  slang_build_runner: ^4.7.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"
  remove_alpha_ios: true


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Thin.otf
          weight: 100

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
