name: resident_live
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  dependency_validator: any


flutter:
  uses-material-design: true
