name: resident_live
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.3.2 <4.0.0'

scripts: 
  gen: dart run build_runner watch
  run: flutter run -t lib/app/main.dart
  reset: |
    flutter clean 
    flutter pub get

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  bloc: ^8.1.4
  flutter_animate: ^4.5.0
  country_list_pick: ^1.0.1+6
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.2.8
  flutter_vibrate: ^1.3.0
  share_plus: ^10.0.2
  modal_bottom_sheet: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.69.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  chopper_generator: ^7.0.4

  dependency_validator: any
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/
