name: resident_live
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

scripts: 
  gen: dart run build_runner watch
  gen_locales: dart run intl_utils:generate
  run: flutter run -t lib/app/main.dart
  run-release: flutter run -t lib/app/main.dart --release
  deploy: cd ios && fastlane beta
  clean: |
    flutter clean 
    flutter pub get

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  mixpanel_flutter: ^2.3.3
  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  bloc: ^8.1.4
  flutter_animate: ^4.5.0
  country_list_pick: ^1.0.1+6
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.2.8
  flutter_vibrate: ^1.3.0
  share_plus: ^10.1.0
  modal_bottom_sheet: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.69.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  app_settings: ^5.1.1
  soft_edge_blur: ^0.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  intl_utils: ^2.8.2

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  chopper_generator: ^7.0.4

  dependency_validator: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  class_name: S
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/
    - secrets.json


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Thin.otf
          weight: 100

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
