name: resident_live
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: '>=3.3.2 <4.0.0'

scripts: 
  gen: dart run build_runner watch
  gen_locales: dart run easy_localization:generate -S assets/translations -f keys
  run: flutter run -t lib/app/main.dart
  clean: |
    flutter clean 
    flutter pub get

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  bloc: ^8.1.4
  flutter_animate: ^4.5.0
  country_list_pick: ^1.0.1+6
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.2.8
  flutter_vibrate: ^1.3.0
  share_plus: ^10.1.0
  modal_bottom_sheet: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.69.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  easy_localization: ^3.0.7  # Use the latest version
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  app_settings: ^5.1.1
  soft_edge_blur: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  intl_utils: ^2.8.2

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  chopper_generator: ^7.0.4

  dependency_validator: any
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/
    - assets/translations/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans/WorkSans-Thin.ttf
          weight: 100

