name: resident_live
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  bloc: ^8.1.4
  flutter_animate: ^4.5.0
  country_list_pick: ^1.0.1+6
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  chopper_generator: ^7.0.4

  dependency_validator: any


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
