source "https://rubygems.org"

gem "cocoapods", "~> 1.16.2"
gem "fastlane", "~> 2.227.0"
gem "minitest", ">= 5.1"
gem "activesupport", "~> 7.2.2"
gem "rubyzip", "~> 2.3.0"  # Добавляем rubyzip
gem "abbrev"
