name: domain
description: Domain layer with entities, repositories and use cases
version: 1.0.0


environment:
  sdk: '>=3.0.0 <4.0.0'

scripts: 
  gen: dart run build_runner watch

dependencies:
  freezed_annotation: 2.4.1

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  intl_utils: ^2.8.2
  pedantic: ^1.11.0
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  chopper_generator: ^7.0.4
